# Permalinks
#

# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:title
# permalink:           pretty
# relative_permalinks: true

# Setup
title:               Leo Kwan
tagline:             Blog
url:                 http://leojkwan.github.io
paginate:            5
paginate_path:       "page:num"
baseurl:             ""
gems: [jekyll-paginate, jekyll-watch, jekyll-assets]

# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Leo Kwan
  url:               https://twitter.com/leojkwan
  email:             leojkwan@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:

exclude: ['node_modules', 'Gruntfile.js','package.json',‘css’, ‘_scss’]

# Do not erase the css directory in the _site output
# It rebuilds every build.
keep_files: ['_site/css']

kramdown:
  input: GFM
  syntax_highlighter: rouge
highligher: rouge

#########################
# Plugin: jekyll-assets #
#########################

# Assets Pipeline
assets:
  sources:
    - _assets
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
